# NOTE: update this with your service name
service: my-first-app

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    CONFIG_PERSONS_TABLE: ${self:custom.tableNames.persons}
    CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}
custom:
  endpoints:
    dynamodb-url: 'http://localhost:8000'
  tableNames:
    persons: 'ERWTE_Files'
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
Resources:
  PersonsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: fileId
          AttributeType: S
      KeySchema:
        - AttributeName: fileId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.tableNames.persons}  

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
